default: &DEFAULT
  TypeAheadContextPath: /search2/search/suggested2
  AreaContextPath: /lookup/internal/area/locate
  TypeAheadToken: e575fa3c913a4c91b224f66969e63a66
dev:
  <<: *DEFAULT
  ReindexedClusterPath: https://vpc-reindex-nxvfoonqh3jbcz37uu6b4zfov4.us-east-1.es.amazonaws.com:443/
  BasketBaseApiPath: https://api.basketsavings.com
  Env: dev
test:
  <<: *DEFAULT
  ReindexedClusterPath: https://vpc-reindex-nxvfoonqh3jbcz37uu6b4zfov4.us-east-1.es.amazonaws.com:443/
  BasketBaseApiPath: https://api.basketsavings.com
  Env: test
prod:
  <<: *DEFAULT
  ReindexedClusterPath: https://vpc-reindex-nxvfoonqh3jbcz37uu6b4zfov4.us-east-1.es.amazonaws.com:443/
  BasketBaseApiPath: https://api.basketsavings.com
  Env: prod
