package _const


const PROUCTPRICEINDEX string = "prices"
const (
	LATITUDEFIELD          string = "latitude"
	LONGITUDEFIELD         string = "longitude"
	FINALPRICEFIELD        string = "finalPrice"
	BUSINESSVALUEFIELD     string = "typeBusinessValue"
	POPULARITYFIELD        string = "popularity"
	TOTALPRICESCOREFIELD   string = "totalPricesScore"
	PRODUCTIDFIELD         string = "productId"
	STOREIDFIELD           string = "storeId"
	CATEGORYIDFIELD        string = "categoryId"
	TYPEIDFIELD            string = "typeId"
	BRANDIDFIELD           string = "brandId"
	PRICESTATUSFIELD       string = "priceStatus"
	PRODUCTSTATUSFIELD     string = "productStatus"
	LOCATIONFIELD          string = "location"
	METROAREAIDFIELD       string = "metroAreaId"
	CHAINIDFIELD           string = "chainId"
	CITYIDFIELD            string = "cityId"
	ZIPIDFIELD             string = "zipCodeId"
	LISTPRICEFIELD         string = "listPrice"
	LISTPRICEPERONEFIELD   string = "listPricePerOne"
	LISTQUANTITYFIELD      string = "listQuantity"
	LISTPRICEUSERIDFIELD   string = "listPriceUserId"
	SALEPRICEPERONEFIELD   string = "salePricePerOne"
	SALEPRICETYPEID        string = "salePriceTypeId"
	SALEVALUE1FIELD        string = "saleValue1"
	SALEVALUE2FIELD        string = "saleValue2"
	SALEVALUE3FIELD        string = "saleValue3"
	SALEPRICEUSERIDFIELD   string = "salePriceUserId"
	SALEENDDATEFIELD       string = "saleEndDate"
	COUPONPRICEPERONEFIELD string = "couponPricePerOne"
	COUPONPRICETYPEIDFIELD string = "couponPriceTypeId"
	COUPONVALUE1FIELD      string = "couponValue1"
	COUPONVALUE2FIELD      string = "couponValue2"
	COUPONVALUE3FIELD      string = "couponValue3"
	COUPONURIFIELD         string = "couponUri"
	COUPONENDDATEFIELD     string = "couponEndDate"
	UNITPRICEPERONEFIELD   string = "unitPricePerOne"
	UNIDESCFIELD           string = "unitDesc"
)
